# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  ios:
    runs-on: macos-latest
    needs: ['build']
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Install Go Mobile
      run: make install-go-mobile

    - name: Build
      run: make ios

    - name: Archive Build Output
      uses: actions/upload-artifact@v4
      with:
        name: AlgoSDK.xcframework
        path: output/AlgoSDK.xcframework
